In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../GSE68086_TEP_data_matrix.csv')
series = pd.read_csv('../GSE68086_series_matrix.csv')
data_df = pd.DataFrame(data)
series_df = pd.DataFrame(series)

### data: these are the raw counts

In [3]:
data_df.head()

,Unnamed: 0,3-Breast-Her2-ampl,8-Breast-WT,10-Breast-Her2-ampl,Breast-100,15-Breast-Her2-ampl,16-Breast-WT,21-Breast-WT,33-Breast-Her2-ampl,42-Breast-Her2-ampl,...,MGH-NSCLC-L20-TR500,MGH-NSCLC-L22-TR462,MGH-NSCLC-L23-TR524,MGH-NSCLC-L25-TR480,MGH-NSCLC-L39-TR519,MGH-NSCLC-L40-TR520,MGH-NSCLC-L51-TR521,MGH-NSCLC-L58-TR525,MGH-NSCLC-L59-TR522,MGH-NSCLC-L65-TR523
0,ENSG00000000003,0,0,0,0,17,0,0,0,0,...,0,5,10,9,0,0,0,0,0,0
1,ENSG00000000005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000000419,44,14,16,8,9,0,139,108,55,...,2,41,40,15,1,0,13,0,0,10
3,ENSG00000000457,26,1,14,0,4,20,1,26,24,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000000460,81,98,18,17,0,20,144,26,97,...,23,1,6,22,30,0,1,50,6,2

In [4]:
data_df.shape

(57736, 286)

In [5]:
data_df.nunique()

Unnamed: 0             57736
3-Breast-Her2-ampl      1120
8-Breast-WT             1051
10-Breast-Her2-ampl     1022
Breast-100               611
                       ...
MGH-NSCLC-L40-TR520      709
MGH-NSCLC-L51-TR521      888
MGH-NSCLC-L58-TR525     1061
MGH-NSCLC-L59-TR522      741
MGH-NSCLC-L65-TR523      965
Length: 286, dtype: int64

### series: pacient data

In [6]:
series_df.shape

(285, 46)

In [7]:
series_df.head(20)

,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1.1,...,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_relation.1,!Sample_supplementary_file_1,!series_matrix_table_begin,"""ID_REF""",!series_matrix_table_end
0,"""GSM1662534""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""3-Breast-Her2-ampl""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662534""",NaN
1,"""GSM1662535""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""8-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662535""",NaN
2,"""GSM1662536""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""10-Breast-Her2-ampl""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662536""",NaN
3,"""GSM1662537""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Breast-100""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662537""",NaN
4,"""GSM1662538""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""15-Breast-Her2-ampl""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662538""",NaN
5,"""GSM1662539""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""16-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662539""",NaN
6,"""GSM1662540""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""21-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662540""",NaN
7,"""GSM1662541""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""33-Breast-Her2-ampl""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662541""",NaN
8,"""GSM1662542""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""42-Breast-Her2-ampl""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662542""",NaN
9,"""GSM1662543""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Breast-454""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662543""",NaN
10,"""GSM1662544""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""48-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662544""",NaN
11,"""GSM1662545""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""50-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662545""",NaN
12,"""GSM1662546""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""55-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662546""",NaN
13,"""GSM1662547""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Type-Unknown-6""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662547""",NaN
14,"""GSM1662548""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Breast-564""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662548""",NaN
15,"""GSM1662549""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""59-Breast-WT""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662549""",NaN
16,"""GSM1662550""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Breast-590""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662550""",NaN
17,"""GSM1662551""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Breast-60""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662551""",NaN
18,"""GSM1662552""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""Breast-603""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662552""",NaN
19,"""GSM1662553""","""Public on Oct 30 2015""","""Apr 21 2015""","""May 15 2019""","""SRA""","""1""","""ALK61-Breast-Her2-unknown""","""Homo sapiens""","""tissue: blood""","""cell type: Thrombocytes""",...,"""Illumina HiSeq 2500""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE""",NaN,"""GSM1662553""",NaN

In [8]:
series_df.columns.str.strip()

Index(['!Sample_geo_accession', '!Sample_status', '!Sample_submission_date',
       '!Sample_last_update_date', '!Sample_type', '!Sample_channel_count',
       '!Sample_source_name_ch1', '!Sample_organism_ch1',
       '!Sample_characteristics_ch1', '!Sample_characteristics_ch1.1',
       '!Sample_characteristics_ch1.2', '!Sample_characteristics_ch1.3',
       '!Sample_characteristics_ch1.4', '!Sample_characteristics_ch1.5',
       '!Sample_molecule_ch1', '!Sample_extract_protocol_ch1',
       '!Sample_extract_protocol_ch1.1', '!Sample_taxid_ch1',
       '!Sample_description', '!Sample_data_processing',
       '!Sample_data_processing.1', '!Sample_data_processing.2',
       '!Sample_data_processing.3', '!Sample_data_processing.4',
       '!Sample_data_processing.5', '!Sample_platform_id',
       '!Sample_contact_name', '!Sample_contact_email',
       '!Sample_contact_laboratory', '!Sample_contact_department',
       '!Sample_contact_institute', '!Sample_contact_address',
       '!Sample_contact_city', '!Sample_contact_zip/postal_code',
       '!Sample_contact_country', '!Sample_data_row_count',
       '!Sample_instrument_model', '!Sample_library_selection',
       '!Sample_library_source', '!Sample_library_strategy',
       '!Sample_relation', '!Sample_relation.1',
       '!Sample_supplementary_file_1', '!series_matrix_table_begin',
       '"ID_REF"', '!series_matrix_table_end'],
      dtype='str')

In [9]:
series_df.groupby("!Sample_characteristics_ch1.4")["!Sample_submission_date"].apply(list)

!Sample_characteristics_ch1.4
"batch: Batch01"                       ["Apr 21 2015", "Apr 21 2015"]
"batch: Batch02"    ["Apr 21 2015", "Apr 21 2015", "Apr 21 2015", ...
"batch: Batch03"    ["Apr 21 2015", "Apr 21 2015", "Apr 21 2015", ...
"batch: Batch04"    ["Apr 21 2015", "Apr 21 2015", "Apr 21 2015", ...
"tissue: blood"     ["Jul 10 2015", "Jul 10 2015", "Jul 10 2015", ...
Name: !Sample_submission_date, dtype: object

In [10]:
series_df['!Sample_submission_date'].value_counts()

!Sample_submission_date
"Apr 21 2015"    245
"Jul 10 2015"     40
Name: count, dtype: int64

### series tidy

In [11]:
def unquote(x):
    '''GEO values arrive triple-quoted through the CSV round-trip: "\"\"\"GSM1662534\"\"\"".'''
    return np.nan if pd.isna(x) else str(x).strip().strip('"')

series_clean = series_df.map(unquote)    # working copy, in memory only
series_df.shape

ch_cols = [c for c in series_clean.columns if c.startswith("!Sample_characteristics_ch1")]

key_of = lambda s: s.split(":")[0].strip() if isinstance(s, str) and ":" in s else "<no key>"
key_pattern = series_clean[ch_cols].apply(lambda row: tuple(key_of(v) for v in row), axis=1)

# print(key_pattern.value_counts().to_string(), "\n")
# ...and the 40 rotated rows are exactly the second submission wave:
# print(pd.crosstab(series_clean["!Sample_submission_date"],
                #   key_pattern.map(lambda p: "rotated" if p[0] != "tissue" else "original")))

# 3. Parse by key -> tidy sample sheet: the same columns as 01_sample sheet creation.R, plus gsm.
#    (Mirrors what GEOquery's pData() hands the R scripts, which is why
#     01_sample sheet creation.R is unaffected by the key-order shift.)
def parse_characteristics(row):
    out = {}
    for v in row:
        if isinstance(v, str) and ":" in v:
            k, _, val = v.partition(":")
            out[k.strip()] = val.strip()
    return pd.Series(out)

chars = series_clean[ch_cols].apply(parse_characteristics, axis=1).rename(
    columns={"cancer type": "group", "patient id": "patient", "mutational subclass": "subclass"}
)

series_tidy = pd.concat(
    [
        series_clean["!Sample_source_name_ch1"].rename("sample"),   # join key to the counts
        series_clean["!Sample_geo_accession"].rename("gsm"),
        chars[["batch", "group", "subclass", "patient"]],
    ],
    axis=1,
)

# Deliberately left out: 'tissue' (always blood) and 'cell type' (always thrombocytes) are constant,
# and 'submission_date' / the !Sample_description note stay in series_clean if ever needed.
print(list(series_tidy.columns))
series_tidy.head()

['sample', 'gsm', 'batch', 'group', 'subclass', 'patient']

,sample,gsm,batch,group,subclass,patient
0,3-Breast-Her2-ampl,GSM1662534,Batch03,Breast,HER2+,Breast-03
1,8-Breast-WT,GSM1662535,Batch03,Breast,wt,Breast-08
2,10-Breast-Her2-ampl,GSM1662536,Batch03,Breast,HER2+,Breast-10
3,Breast-100,GSM1662537,Batch04,Breast,Triple Negative,Breast-100
4,15-Breast-Her2-ampl,GSM1662538,Batch03,Breast,HER2+,Breast-15

In [12]:
# 4. The variables, and the batch/group confounding that 04_DESeq2.R models with ~ batch + group
for col in ["group", "batch", "subclass"]:
    print(f"--- {col} ---")
    print(series_tidy[col].value_counts().to_string(), "\n")

print("patients:", series_tidy.patient.nunique(), "unique for", len(series_tidy), "samples",
      "-> one sample per patient\n")
pd.crosstab(series_tidy.group, series_tidy.batch, margins=True)

--- group ---
group
Lung             60
HC               55
CRC              42
GBM              40
Breast           39
Pancreas         35
Hepatobiliary    14

--- batch ---
batch
Batch03    103
Batch04     87
Batch02     53
Batch06     30
Batch05     10
Batch01      2

--- subclass ---
subclass
wt                 175
KRAS                63
EGFR                13
HER2+               10
EGFR, MET            8
Triple Negative      6
PIK3CA               6
HER2+, PIK3CA        2
MET                  1
KRAS, MET            1

patients: 285 unique for 285 samples -> one sample per patient

batch          Batch01  Batch02  Batch03  Batch04  Batch05  Batch06  All
group
Breast               0        0       15        9        6        9   39
CRC                  0        4       21       13        1        3   42
GBM                  2       12       15       11        0        0   40
HC                   0       16       15       24        0        0   55
Hepatobiliary        0        1        7        5        0        1   14
Lung                 0       19        7       14        3       17   60
Pancreas             0        1       23       11        0        0   35
All                  2       53      103       87       10       30  285